name: Build and Deploy
on:
  push:

jobs:
  build-lint-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn build

      - name: add github pages cname file
        if: startsWith(github.ref, 'refs/tags/')
        run: echo 'curium.technischer.org' > dist/CNAME

      - name: Deploy 🚀
        if: startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist
